from typing import Any, Tuple
from langchain_core.tools import tool

# @tool
# def Add(a: int,b: int)->int:
#     """Add two numbers"""
#     return a+b


# print(Add.invoke({"a":2,"b":3}))

# ## Inspect 
# print(f"Tool Name : {Add.name} ")
# print(f"Tool description : {Add.description}")
# print(f"Tool Args : {Add.args}")

## Configuring the schema
## The @tool decorator offers additional options to configure the schema of the tool (e.g., modify name, description or parse the function's doc-string to infer the schema).

## Tool artifacts:

@tool(response_format="content_and_artifact")
def some_tool(input:str)-> Tuple[str,Any]:

    """
    Tool that processes some input and returns a message along with an artifact.

    Args:
        input_text (str): Input string to process.

    Returns:
        Tuple[str, Any]: 
            - str: Message for the chat model.
            - Any: Some artifact generated by the tool (e.g., dict, image, data).
    """
     # Example processing
    processed_data = {"original": input, "length": len(input)}

    # Message to return to LLM
    message = f"Processed your input of length {len(input)}."

    # Return in content + artifact format
    return message, processed_data

print("some_tool",some_tool.invoke({"input":"Hi How are you ?"}))